### ISSUE TITLE
Facebook will require https soon

### ISSUE THREAD

**Issue by tgreenhalgh** [seeden/react-facebook#106]
I get the following warnings:

The method **FB.login** will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/

The method **FB.getLoginStatus** will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/

The method **FB.api** will soon stop working when called from http pages. Please update your site to use https for Facebook Login. https://developers.facebook.com/blog/post/2018/06/08/enforce-https-facebook-login/

**Comment by seeden** [comment]
@dolynchuk that is true. I am closing it
