### ISSUE TITLE
CSP Violation in v6

### ISSUE THREAD

**Issue by Reinkaos** [seeden/react-facebook#110]
Hey,

After upgrading the react-facebook plugin to version 6 I have found that the Facebook Comment plugin doesn't comply with our CSP policy.

The violation is as following:

`all.js:22 Refused to execute inline event handler because it violates the following Content Security Policy directive: Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.`

Please fix or provide a way that a nonce can be passed through the component as props so that we can whitelist it in our CSP. 

Thanks,
Richard

**Comment by Reinkaos** [comment]
Hey @seeden,

Thanks for your reply, are you saying that the CSP violation is built into how Facebook deliver their SDK?

It does appear that way as I haven't been able to get it to work with their examples either. Do you know if this has changed recently?

Facebook used to work fine with our CSP policy.

Thanks for your reply,
Richard

**Comment by seeden** [comment]
Maybe their change loading of the SDK I will check

**Comment by Reinkaos** [comment]
Thank you!

**Comment by seeden** [comment]
The link is correct as you can see here
https://developers.facebook.com/docs/javascript/quickstart
