### ISSUE TITLE
Login > Token is undefined

### ISSUE THREAD

**Issue by glenngijsberts** [seeden/react-facebook#117]
We have implemented the `Login` component in our application. Unfortunately we have a bug that's a bit annoying.

<img width="586" alt="screenshot 2019-01-18 at 14 43 37" src="https://user-images.githubusercontent.com/14276144/51390540-ddcb1e80-1b2f-11e9-8c74-14798871fc7d.png">

The error is coming from the `onError` prop that is provided with the component. It happens after authorising by Facebook using the `handleClick` render prop. The second time I call this function it will work, but that's obvs a bit annoying.

I investigated different versions but none of them seem to work. Used version `6.0.15` and even versions below. `6.0.4` and `6.0.5` are having different issues.

**Comment by seeden** [comment]
Fixed in the latest version
