### ISSUE TITLE
How to show user profile

### ISSUE THREAD

**Issue by aditya1994** [seeden/react-facebook#120]
import React, { Component} from 'react';
import { FacebookProvider, Profile } from 'react-facebook';

export default class Example extends Component {
  handleChange = (response) => {
    console.log(response);
  } 

  render() {
    return (
      <FacebookProvider appId="123456789">
        <Profile>
          {({ loading, profile }) => (
            <div>
              {profile.picture}
              {profile.name} 
            </div>
          )}
        </Profile>
      </FacebookProvider>    
    );
  }
}

In this code, how do i pass the link/id of the profile to be shown?

**Comment by seeden** [comment]
You can use profile.link if you have access to user's link
