### ISSUE TITLE
Each widget call taking 5 mb of data

### ISSUE THREAD

**Issue by aditya1994** [seeden/react-facebook#124]
Hello, 

I am loading many facebook posts like this:

`<FacebookProvider appId="610139779436551"><div key = {i + listVar_facebook[i]} ><EmbeddedVideo height='400' href={listVar_facebook[i]} width='420' /></div></FacebookProvider>
`

The library is making redundant requests again and again. Any parameter to set to stop sending these calls?

**Comment by seeden** [comment]
Use FacebookProvider just once on your site
