### ISSUE TITLE
Tagged users don't get notifications from FB

### ISSUE THREAD

**Issue by pete0877** [seeden/react-facebook#126]
Hi, 

I noticed that the Comments component has an issue (but I'm not sure where / how to resolve it -- could be part of FB app config). 

When you @ mention a user (and even check the "Also post on Facebook" option) the text area allows you to complete it and the name shows up underlined below once the comment is posted BUT the user I mention never actually gets notified on FB platform. 

Do you know if this is a FB app setting or some sort of security block by FB?
Yes, our app is Live. 

Thank you!

**Comment by seeden** [comment]
It looks like a bug of the facebook. I am just providing container for components.

**Comment by pete0877** [comment]
Thanks Zlatko. I'll reach out to their developer forum.
