### ISSUE TITLE
TypeError: Cannot read property 'Consumer' of undefined

### ISSUE THREAD

**Issue by dantman** [seeden/react-facebook#128]
I'm getting a `TypeError: Cannot read property 'Consumer' of undefined` error when I try to use the Page component.

This appears to be because `src/Initialize.jsx` uses `import { FacebookContext } from './FacebookProvider';` but `src/FacebookProvider.jsx` does not export a `FacebookContext`.

This can probably be fixed by changing `src/Initialize.jsx` to use `import FacebookContext from './FacebookContext';` .

**Comment by seeden** [comment]
pushed new version with fixed context

**Comment by dantman** [comment]
Thanks
