### ISSUE TITLE
web page open in ins by webview can not login by LoginButton

### ISSUE THREAD

**Issue by stevex2012** [seeden/react-facebook#133]
I put my page in ins app,open it by webview.
when I open my page in ins app by webview. 
I use the LoginButton and I click the button .my page jumb to fb's page,and then I 
input my fb account,login success; but when return to my page it did no do the onCompleted or onError functions and nothing mention me . 
Why ?,it seems LoginButton  components worked but somewhere wrong;

**Comment by glenngijsberts** [comment]
Can you maybe clarify your issue a bit more? Maybe add some code, or some examples how you're using it.
