### ISSUE TITLE
connect.facebook.net/en_US/sdk.js is down

### ISSUE THREAD

**Issue by peteroid** [seeden/react-facebook#14]
I just noticed that [https://connect.facebook.net/en_US/sdk.js](https://connect.facebook.net/en_US/sdk.js) is down for some reason.

I need to change `.net` to `.com` to make it work.

**Comment by seeden** [comment]
Hi @peteroid. I can provide new property but .net domain is working for me.

**Comment by seeden** [comment]
this feature is available in new release
