### ISSUE TITLE
Update scope with login

### ISSUE THREAD

**Issue by gbreux** [seeden/react-facebook#140]
Hi,

I wonder if it's just me or if it's a normal behavior but if, for example, I ask for user's scope `email` with `<Login scope="email"/>` and then later I ask for user's scope `users_photos`  with `<Login scope="email,users_photos"/>` (or just `<Login scope="users_photos"/>`, or if I asked for `<Login scope="email,users_photos"/>` first but the user declined and asked again for these scopes), the user is not asked to update its permissions the second time and will always get the first choice even though FB.api should allow permission's update: https://developers.facebook.com/docs/facebook-login/permissions/overview

The only way to update the scope is to uninstall the app from facebook settings manually. 🤔 

Thanks

**Comment by seeden** [comment]
you can use 
  rerequest?: boolean,
  reauthorize?: boolean,

more info you can find in the fb documentation
