### ISSUE TITLE
Any update on releasing support for Customer Chat ?

### ISSUE THREAD

**Issue by pitkes22** [seeden/react-facebook#142]
Hi, I have a problem with making Customer Chat working and I noticed that it seems to already been resolved ( #132 ) however those changes are not published to NPM. Is there any plan to release a new version somewhere in the near future?

**Comment by seeden** [comment]
Hi @pitkes22 
I am sorry, I was busy. I will try to release it this week

**Comment by SanderPeeters** [comment]
@seeden Any updates on this?

**Comment by seeden** [comment]
released new version 8.1.2 do not forget to use attribute chatSupport for FacebookProvider
