### ISSUE TITLE
CustomChat not working

### ISSUE THREAD

**Issue by phamvanhiepvn** [seeden/react-facebook#145]
I'm trying use customChat but it's not working in compoent
This is my code: 

`import { FacebookProvider, CustomChat } from 'react-facebook';`
`render() {
return (
<FacebookProvider appId="appId" wait={true}>
    <CustomChat pageId="pageId" minimized="false"/>
</FacebookProvider>
)
}`
I did add wait={true} but seen it is not init https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js
Can you help me ?

**Comment by seeden** [comment]
why are u using wait ?

**Comment by seeden** [comment]
released new version
