### ISSUE TITLE
Cannot use boolean with 'mobile' props in Comments component

### ISSUE THREAD

**Issue by c0dester** [seeden/react-facebook#148]
I found, that it doesn't matter if I use `true` or `false` with `mobile` prop. Comments will always display as mobile. I need to use `undefined` instead of `false`. It is not convenient, since when I use f.e. react-media, I would do:

```javascript
<Media
  queries={{
    mobile: {
      maxWidth: 768,
    },
    desktop: {
      minWidth: 769,
    },
  }}
>
  {matches => (
    <Comments
      href="HREF"
      mobile={matches.mobile}
    />
  )}
</Media>
```

Instead of that I have to use it this way:

```javascript
<Media
  queries={{
    mobile: {
      maxWidth: 768,
    },
    desktop: {
      minWidth: 769,
    },
  }}
>
  {matches => (
    <Comments
      href="HREF"
      mobile={matches.mobile || undefined}
    />
  )}
</Media>
```

**Comment by seeden** [comment]
Why not matches.mobile || false

**Comment by c0dester** [comment]
Because as I wrote, it takes true or undefined. False acts as true

**Comment by seeden** [comment]
Ahh I see. Interesting.

**Comment by c0dester** [comment]
Not sure if you understood me correctly. I'm talking about Comments `mobile` prop - it accepts true or undefined, false acts like true. I'm not talking about react-media.

**Comment by seeden** [comment]
Yeah, I understand it. It looks like a problem in the facebook sdk. Because valid false value is to use this component without mobile property.
