### ISSUE TITLE
Facebook login token

### ISSUE THREAD

**Issue by wallverb** [seeden/react-facebook#15]
Would it be possible to get entire token with `Login` `onSubmit` - right now it only gives us `signedRequest` - but I would like to get `accessToken` as well - so I could verify data on server side . Thanks

**Comment by seeden** [comment]
Yes that will be a nice feature

**Comment by lakshyaranganath** [comment]
https://github.com/seeden/react-facebook/pull/21

is there anyway we can get this merged quickly?

**Comment by seeden** [comment]
It is merged already I will release new version in few hours

**Comment by lakshyaranganath** [comment]
Oh great, thanks a lot!

**Comment by seeden** [comment]
Released new version 2.2.1
