### ISSUE TITLE
fb login not working with scope business_management

### ISSUE THREAD

**Issue by kacsokz** [seeden/react-facebook#161]
I made a 2 min screencast to show the bug to a colleague of mine, but it will work for this demonstration. The login does not work with the scope: business_management. Have you seen this issue before? 

Thanks!
Casey

**Comment by seeden** [comment]
Hi, try to add property reauthorize. More information you can find here: https://developers.facebook.com/docs/facebook-login/reauthentication/

**Comment by kacsokz** [comment]
Hi, thanks for getting back to me
The login does reauthorize naturally, as long as business_management is not in the scopes. It breaks before you can authorize it the first time. 

I did try adding the auth_type="reauthenticate" and the same issue happens. It works for any scope but business_management

![image](https://user-images.githubusercontent.com/52221616/73095870-bf190980-3ea0-11ea-8de3-1068264fcc03.png)

**Comment by kacsokz** [comment]
Hi, thanks for getting back to me
The login does reauthorize naturally, as long as business_management is not in the scopes. It breaks before you can authorize it the first time.

I did try adding the auth_type="reauthenticate" and the same issue happens. It works for any scope but business_management
![image](https://user-images.githubusercontent.com/52221616/73095952-f2f42f00-3ea0-11ea-96aa-2805e208e776.png)
