### ISSUE TITLE
Like button missing

### ISSUE THREAD

**Issue by alexgarces** [seeden/react-facebook#17]
When I implement the Like button, it seems like the iframe is missing something because the button is not showing at all, even if some of the styles seem to be loaded.

**Comment by seeden** [comment]
Can you provide more information?

**Comment by resendefreitas** [comment]
Same here,
<img width="373" alt="screen shot 2016-10-14 at 3 15 51 pm" src="https://cloud.githubusercontent.com/assets/8530905/19398071/38621b36-9221-11e6-9f24-c2481f971823.png">

https://www.facebook.com/v2.5/plugins/like.php?action=like&app_id=.... request is returning 500

**Comment by resendefreitas** [comment]
Oh never mind, I had copied the wrong AppID.
But still I implemented just like the usage exemple, iframe code is there, but style is height=0 and i can't overight it :/

**Comment by seeden** [comment]
Hi @resendefreitas 

I am little bit confused. I can not find any information about height in the documentation
https://developers.facebook.com/docs/plugins/like-button

Can you provide more information?

**Comment by seeden** [comment]
Do you want to have own className?

**Comment by resendefreitas** [comment]
Hey @seeden ,
I implemented just like this:
`import React, { Component} from 'react';
import FacebookProvider, { Like } from 'react-facebook';

export default class LikeComponent extends Component {
  render() {
    return (
      <FacebookProvider appID="202115750200057">
        <Like href="http://www.facebook.com/avidadequem" colorScheme="dark" showFaces share />
      </FacebookProvider>
    );
  }
}`
Using my correct app id and page url.
Importing that component puts this on the html:
<img width="373" alt="screen shot 2016-10-16 at 2 21 30 pm" src="https://cloud.githubusercontent.com/assets/8530905/19418876/f3a486d2-93ab-11e6-838d-88e94b66490c.png">
But nothing shows on my view. 
Should I manipulate with my own className?

**Comment by seeden** [comment]
Hi @resendefreitas. No do not change className.
First of all you need to use FacebookProvider as singleton. That means only once on your page. It is using context for communication with other react-facebook components.

**Comment by seeden** [comment]
Anyway I can see the correct like button with your href. Are you sure that your facebook application is enabled and you are using correct domain? Please take a look in your console and try to find some debug information from facebook.

**Comment by resendefreitas** [comment]
@seeden Using it as a Singleton solved it for me! Thanks 👍

**Comment by seeden** [comment]
thanks for the information. I am going to add warning when user will use it multiple times.
