### ISSUE TITLE
Page Component shows nothing

### ISSUE THREAD

**Issue by seniordev0425** [seeden/react-facebook#176]
Hi.
I'd like to use this component to show facebook pages.
Here is my code.

```
<FacebookProvider appId="my-app-id">
         <Page href="https://www.facebook.com/Rafflee-101514858298034/" tabs="timeline" />
</FacebookProvider>
```

But this shows nothing.
I will appreciate any helps.

**Comment by hiep294** [comment]
you should create new app in https://developers.facebook.com, then replace app id to "my-app-id"
