### ISSUE TITLE
Like component not working any more, when user is logged-in

### ISSUE THREAD

**Issue by Koli14** [seeden/react-facebook#186]
I use the Like component, and it's working as expected when users are not logged into FB, but when they are logged in, nothing appears.
It was working correctly earlier. Is it related to this: https://github.com/seeden/react-facebook/issues/174 ?
Does other experience the same? 
Here is an example page, where it's not working: https://szinhaz.online/a-fuggetlenekert-jatszik-online-az-orkeny-szinhaz/
On the bottom of the article there is a Like component:
` <FacebookProvider appId='12345' language='hu_HU'>
          <Box overflowX={['scroll', 'auto']} minH='40px' my='20px'>
            <Like
              href={post.link}
              colorScheme='light'
              layout='standard'
              size='large'
              width='366px'
              share
            />
          </Box>
        </FacebookProvider>`
Can the problem be by my FB App settings?

**Comment by coltenkrauter** [comment]
Did you figure anything out for this?

**Comment by Koli14** [comment]
I don't really remember, but I think the problem was by Facebook, and it was solved without my  contribution.
