### ISSUE TITLE
Trying to use EmbebedPost but its not working, Why?

### ISSUE THREAD

**Issue by pedrotomas50** [seeden/react-facebook#187]
![Screenshot 2021-03-02 at 17 46 20](https://user-images.githubusercontent.com/63668673/109692013-ee0fad80-7b7f-11eb-9a0c-3201df1b9bd5.png)
![Screenshot 2021-03-02 at 17 47 07](https://user-images.githubusercontent.com/63668673/109692020-ef40da80-7b7f-11eb-8bd8-4771178b69b6.png)

**Comment by seeden** [comment]
Try to use ```<FAcebookProvider debug>``` Maybe you will get answer in console
