### ISSUE TITLE
data-order-by Parameter not working

### ISSUE THREAD

**Issue by SteGreig** [seeden/react-facebook#188]
Hi, I'm trying to amend the order of Facebook comments can't seem to get the data-order-by parameter to work - it just always shows the oldest comments first, when I want the exact opposite.

This is what I have tried but the comments are just always set to "Oldest" no matter what I try.

`<FacebookProvider wait data-order-by="reverse_time" appId="xxxxxxxxxxxxxxx">
     <Comments href="https://www.facebook.com/" data-order-by="reverse_time" />
</FacebookProvider>`

Any help would be appreciated.

**Comment by sirshurak** [comment]
Hi, the right property to use is "orderBy", look at the options for Comments:

data-colorscheme={colorScheme}
data-numposts={numPosts}
data-href={href}
data-order-by={orderBy}
data-width={width}
data-skin={colorScheme}
data-mobile={mobile}

**Comment by SteGreig** [comment]
Thank you! I couldn't see this in the documentation - might be worth adding.

**Comment by seeden** [comment]
Closing it :)
