### ISSUE TITLE
Facebook API upcoming deprecations

### ISSUE THREAD

**Issue by rafamem** [seeden/react-facebook#193]
Please update the Facebook Api version... Thank you!

**API Version Deprecations:**

As part of Facebook’s Graph API and Marketing API, please note the upcoming deprecations:

- August 3, 2021: Graph API v3.3 will be deprecated and removed from the platform
- August 25, 2021 Marketing API v9.0 will be deprecated and removed from the platform
- October 4, 2021: Marketing API v10.0 will be deprecated and removed from the platform
- November 2, 2021: Graph API v4.0 will be deprecated and removed from the platform
- February 3, 2022: Graph API v5.0 will be deprecated and removed from the platform

**Comment by vaibhavsah** [comment]
@rafamem Any suggestions about the changes we need to do at our end to fix this.

**Comment by seeden** [comment]
Use version 9
