### ISSUE TITLE
Share is not working as expected

### ISSUE THREAD

**Issue by lahoti-piyush** [seeden/react-facebook#194]
I have implemented below code and it get trigger from a model popup of my website

```
import React, { Component} from 'react';
import { FacebookProvider, Share } from 'react-facebook';

export default class Example extends Component {
  render() {
    return (
      <FacebookProvider appId="123456789">
        <Share href="http://www.facebook.com" >
          {({ handleClick, loading }) => (
            <button type="button" disabled={loading} onClick={handleClick}>Share</button>
          )}
        </Share>
      </FacebookProvider>
    );
  }
}

```

On Desktop it open new window, share given href on FB and close that window.
But while doing same from mobile browser it open new window share link on FB and redirect to parent url. It should get close after share and come to parent window.

Even I have tried 
`display={isMobile?'touch':'popup'} mobileIframe={isMobile}`

**Comment by seeden** [comment]
Can you try latest version?
