### ISSUE TITLE
Uncaught (in promise) Invariant Violation: Minified invariant #47458; %s Params: %s

### ISSUE THREAD

**Issue by ahmadchand** [seeden/react-facebook#198]
I had implemented Facebook Login and Messenger Customer Chat and everything works fine but now this error start to popping out recently.

Any help would be appreciated.

![image](https://user-images.githubusercontent.com/56013146/145353603-a57f4b9e-d79c-437b-94ef-58abd90662a6.png)

**Comment by khuonghieu** [comment]
I was having the same issue. In the log, it said that logging in would not be allowed by http. You might need https to use this package, consider using ngrok.
![image](https://user-images.githubusercontent.com/32558984/145361118-c37cfe15-d6f0-48bf-9dcc-83f59c9836ec.png)

**Comment by themodegroup** [comment]
> I was having the same issue. In the log, it said that logging in would not be allowed by http. You might need https to use this package, consider using ngrok. ![image](https://user-images.githubusercontent.com/32558984/145361118-c37cfe15-d6f0-48bf-9dcc-83f59c9836ec.png)

We are in production mode using https still we get the error

**Comment by emahmi** [comment]
I am also using `https` and got the issue

**Comment by rafamem** [comment]
Please update the plugin with the new Facebook API or accept the merge requests.

**Comment by seeden** [comment]
New version is available. Closing it
