### ISSUE TITLE
Login only works the first time.

### ISSUE THREAD

**Issue by jesse-robertson** [seeden/react-facebook#2]
Hey guys, awesome project.  I'm having an issue with the Login component though.

My use case:
1. On load, users directed to login page
2. Users can click button to log in via facebook (works great!)
3. Users can click 'logout', which takes them back to the login page (via react-router)
4. Users can click button again to log back in via facebook (Does not work)

The problem is that the callback passed to `this.context.facebook.whenReady()` in Login's `componentDidMount()` is only executed the first time, which results in `this.state.facebook` and `this.state.working` both being undefined, which means `isWorking()` always returns true, which shortcuts the `onSubmit()` method.

I believe that the `facebook.whenReady` callback remains unexecuted because the `this._initialized` variable in src/Facebook.js defaults to false on mount and is only set to true if the `_initFB()` method is invoked.  However, this method is only invoked when the facebook sdk script is loaded, which only happens the very first time.

I'm not sure how this change would affect your other components, but I've been able to get my code to work by adding `this._initialized=true` to the `_loadScript()` shortcut: 

````js
const fjs = document.getElementsByTagName('script')[0];
if (document.getElementById('facebook-jssdk')) {
    this._initialized = true;
    return;
}
````

**Comment by seeden** [comment]
Hi @jesse-robertson 

I think that you have a problem with component FacebookProvider.
You need to use it as singleton. That means  you need to use this component in your main react-router route (App component). 

<Route path="/" component={App}>
 // other routes
</Route>

**Comment by jesse-robertson** [comment]
Yes that did the trick.  Thank you.
