### ISSUE TITLE
How to change the locale?

### ISSUE THREAD

**Issue by stelasido** [seeden/react-facebook#200]
I have simple comment component:
`        return (
            <FacebookProvider appId={FB_APP_ID}>
                <Comments href={this.props.url} />
            </FacebookProvider>
        )`
, but the locale is always something different that the language of the page, I have HTML lang attribute like `<html lang="fr", fr the example.`
The url to the FB SDK is always with different locale

**Comment by seeden** [comment]
you can use <FacebookProvider language="fr_FR">
