### ISSUE TITLE
Library doesn't seem to work on Safari / iOS

### ISSUE THREAD

**Issue by Dunky45** [seeden/react-facebook#201]
Hi,

So I'm using facebook comments in our app, everything works fine in Chrome, however on Safari and iOS safari I'm getting this message:

`Refused to display  'https://www.facebook.com/v3.1/plugins/comments.php?blahblahblah'  in a frame because it set 'X-Frame-Options' to 'DENY'.`

Is there any way to bypass this issue?

Thank you all for response!

**Comment by seeden** [comment]
Please try to use version 9 and let me know

**Comment by Dunky45** [comment]
Sorry, I've forgot to reply. 

Yes, downgrading to older version works. The only issue now is that facebook comments are not working in Europe, but that is not issue with this library.

**Comment by seeden** [comment]
I am confused. Which version of my library are you using? version 8 is two years old. Version 9 is new one

**Comment by Dunky45** [comment]
8.1.4 is the version that is working for me on NextJS.
