### ISSUE TITLE
[React] React is not defined

### ISSUE THREAD

**Issue by siamahnaf198** [seeden/react-facebook#205]
Hello, @seeden, I am try to use react facebook in my project. But when I add Facebook provider to my project, It throwing an error like this `ReferenceError: React is not defined`

My Project running with-
1. Next js
2. Typescript

The version I am using-
Latest version `9.0.7`

```
<FacebookProvider appId={process.env.NEXT_PUBLIC_FACEBOOK_APP_ID as string}>
        <FacebookLogins />
 </FacebookProvider>
```

And this is `FacebookLogins.tsx` Component-

```
import { useLogin } from 'react-facebook';

export default function LoginExample() {
    const { login, status, isLoading, error } = useLogin();

    async function handleLogin() {
        try {
            const response = await login({
                scope: 'email',
            });

            console.log(response.status);
        } catch (error: any) {
            console.log(error.message);
        }
    }

    return (
        <button onClick={handleLogin} disabled={isLoading}>
            Login via Facebook
        </button>
    );
}
```

Where I am wrong, How can I solve it.

![image](https://user-images.githubusercontent.com/78312010/191946438-9c31c71c-6402-4bb8-af8f-d97e297e35eb.png)

**Comment by nekmart** [comment]
Same here. Any Solutions. Please help me.

**Comment by azhoang** [comment]
Same here. Any Solutions. Please help me.

**Comment by siamahnaf198** [comment]
Waiting for @seeden reply.

**Comment by seeden** [comment]
I need to bundle library in different way. Meanwhile you can use version 8

**Comment by siamahnaf198** [comment]
But version 8 is not come with typescript. I already install and try version 8.1.4. But it is not come with type declaration. We have to wait for the next version. We are waiting

**Comment by cgrewon** [comment]
I am facing same issue at create-react-app project. please help me
"React is not defined"

**Comment by seeden** [comment]
Can you try latest version?

**Comment by cgrewon** [comment]
yes I have tried with latest version and it is working, but when I try to useShare, nothing happened.. :(
