### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by moonman239** [seeden/react-facebook#207]
When I try to use the React Facebook SDK module in a TypeScript project, I get the following error:

```
TypeScript error: Could not find a declaration file for module 'react-facebook-sdk'. 'C:/Users/moonman239/Documents/HashtagIntel/hashtagintel-website/node_modules/react-facebook-sdk/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/react-facebook-sdk` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-facebook-sdk';` 
```

I tried to install @types/react-facebook-sdk, but no such package exists. 

Could the package authors please add types so that this package is compatible with TypeScript? This will help me guarantee type safety.

Thank you!

**Comment by seeden** [comment]
Hi, @moonman239 react-facebook-sdk is not my package. It is an old fork from my package. I am the author of react-facebook package, which has TypeScript support already.
Anyway, thanks for coffee :)
