### ISSUE TITLE
React : Facebook API is not initialized 

### ISSUE THREAD

**Issue by abhisheksahu2001** [seeden/react-facebook#215]
`import React from "react";
import { FacebookProvider, useLogin } from "react-facebook";

const App = () => {
  const { login, status, isLoading, error } = useLogin();

  async function handleLogin() {
    try {
      const response = await login({
        scope: "email",
      });

      console.log(response.status);
    } catch (error) {
      console.log(error.message);
    }
  }
  return (
    <>
      <button onClick={handleLogin} disabled={isLoading}>
        Login via Facebook
      </button>
    </>
  );
};

export default App;
![Screenshot (2)](https://user-images.githubusercontent.com/76276437/213160690-37044b51-262d-4290-8587-168e10f34d75.png)
`

**Comment by abhisheksahu2001** [comment]
s

**Comment by jimmywong123** [comment]
How do you solve it?

**Comment by tlt254** [comment]
+1
