### ISSUE TITLE
Post embed width under 350px

### ISSUE THREAD

**Issue by camel113** [seeden/react-facebook#36]
I try to embed Facebook post to my website. It works well for screen above 350px large but under this width posts are cut... It seems that the max width for posts is 350px.
What if you want to display facebook post embed for small screen under 350px?
Tried with `widht 100%` but does not work.

```
<FacebookProvider appId="1234">
  <EmbeddedPost href={"https://www.facebook.com/teampulse.ch/posts/"+post} width="100%" />
</FacebookProvider>
```

**Comment by seeden** [comment]
Hi @camel113 .

If you want to use fluid width you need to set width="auto".
More information you can find here:
https://developers.facebook.com/docs/plugins/embedded-posts

Let me know if it is working for you.

**Comment by camel113** [comment]
It does not work... But maybe it's because of parents CSS rules. I should check it independently. I will give you updates later.

**Comment by camel113** [comment]
It works when I add this CSS code
```
.fb-post>span {
    max-width: 100%;
}
.fb-post iframe {
  border: 0;
  display: block;
  margin: 0 auto;
  max-width: 100%;
}
```
Otherwise I have some issue on mobile desktop

**Comment by seeden** [comment]
It is related to facebook. Maybe nice addon to documentation

**Comment by omkarsk98** [comment]
Where will I get the correct appId?

**Comment by seeden** [comment]
you need to create your app (developers.facebook.com)
