### ISSUE TITLE
Warning: setState(...): Can only update a mounted or mounting component

### ISSUE THREAD

**Issue by markotom** [seeden/react-facebook#41]
Hi there!

I got this warning in my application and I think may be there a problem with the Share component:

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the **Share component**.

Do you know why this happening?

Thank you for this library.

**Comment by seeden** [comment]
Can you create working example?

**Comment by markotom** [comment]
It seems to be a conflict with `react-router` module, because the warning appears when changing location:

`parent.js` (rendered on `/` location)
```js
import React from 'react'
import { Link } from 'react-router'

export default () => {
  return (
    <div>
      <Link to='/details'>
        <button type='button'>View</button>
      </Link>
    </div>
  )
}
```
`child.js` (rendered on `/details` location)
```js
import React from 'react'
import Facebook, { Share } from 'react-facebook'

export default () => {
  return (
    <div>
      <Facebook appId='...'>
        <Share href='http://...' quote='Some text'>
          <button type='button'>Share</button>
        </Share>
      </Facebook>
    </div>
  )
}
```

**Comment by seeden** [comment]
I will try to fix it this week

**Comment by shotor** [comment]
@markotom did you ever manage to fix this? Am having the same problem when rendering a dynamic array of components (changes after first render) containing the share component

**Comment by seeden** [comment]
It is fixed in the latest build. Please let me know if it is working for you as well. Thanks
