### ISSUE TITLE
Video Embeds

### ISSUE THREAD

**Issue by samburgers** [seeden/react-facebook#43]
Hi, 

Does this by any chance support facebook video embeds, and the hopefully also the ability to use the player controls `play()` `pause()` etc?

Many thanks!

**Comment by seeden** [comment]
PR is welcome

**Comment by seeden** [comment]
added in new version

**Comment by shikha017** [comment]
Can we embed are Facebook group private videos in our website

**Comment by shikha017** [comment]
Can we embed our facebook group selected group or private videos in our website through this plugin
