### ISSUE TITLE
Update readme.md to include example for Page component

### ISSUE THREAD

**Issue by charliedotau** [seeden/react-facebook#45]
Hi there,

I can't see any examples or doco for using The Page component.  I want to be able to link to, and promote, my Facebook page in my react app.
Thanks

**Comment by seeden** [comment]
PR will be welcome

**Comment by charliedotau** [comment]
hey @seeden . Thanks.  I don't know how to use the Page component, so unable to supply PR.

**Comment by EmilAgren** [comment]
Maybe this helps someone.

I am using the Page component like this:
1. Import
`import FacebookProvider, { Page } from 'react-facebook';`
2. Code
`<FacebookProvider appId="xxxxxx">
					<Page href="https://www.facebook.com/myPage" tabs="none" />
				</FacebookProvider>`

The appId is your facebook app id, obviously.
The href attribute is the url to your facebook page.
These two attributes are the only ones needed to get it working. Although I've added the tabs attribute with value "none" to get rid of the big timeline addition, which is default.

Only problem for me is that I can't get the share-button to appear... for some reason it doesn't show up. Anyone else got a solution for that?

**Comment by advance512** [comment]
Any demo? Real demo of how this stuff looks?
It looks like a very nice library, but if I have no idea how it will actually end up looking, how can I really choose it?

**Comment by artdias90** [comment]
I will provide send a PR asap
