### ISSUE TITLE
Facebook login issue

### ISSUE THREAD

**Issue by shadrech** [seeden/react-facebook#48]
Trying to use login component but keep getting this error:
```FB.login() called before FB.init()```
Code is as follows:
```
<FacebookProvider appId={config.appApi.credentials.deviceId}>
   <Login
      scope="email"
      onResponse={this.handleFBLogin}
      onError={err => console.error("FB LOGIN:", err)}>
    <div className="submit-btn">
      <FacebookLogo />
      <a>Login with Facebook</a>
    </div>
  </Login>
</FacebookProvider>
```

**Comment by graphee-gabriel** [comment]
What is `config.appApi.credentials.deviceId` ?
It seems like a strange name for a Facebook App ID, wouldn't this be a confusion, and maybe the source of your problem?

**Comment by seeden** [comment]
whole API was changed. try new 6.x version
