### ISSUE TITLE
React doesn't recognize appId prop

### ISSUE THREAD

**Issue by chrisalcantara** [seeden/react-facebook#51]
Hello!

When I try rendering the `<FacebookProvider>` component with an `appId`, I get the following message: `React does not recognize the "data-appID" prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase "data-appid" instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

I am using the latest version of `react` and `react-facebook`.

**Comment by seeden** [comment]
Thanks  @chrisalcantara I will take a look on this tomorrow

**Comment by seeden** [comment]
fixed in the last release
