### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by brunosantanarj** [seeden/react-facebook#55]
My application is not be working because react-facebook not transpile from ES6 to es5.
![captura de tela de 2017-11-10 11-50-46](https://user-images.githubusercontent.com/8305178/32661257-6d3314a2-c60d-11e7-8588-da8d5b645ac5.png)

**Comment by seeden** [comment]
are you using nodejs? which version?

**Comment by brunosantanarj** [comment]
Yes. v7.10.1

**Comment by seeden** [comment]
Is it compiled with webpack for browser or are you using it for SSR?

**Comment by brunosantanarj** [comment]
I'm using SSR with Express

**Comment by seeden** [comment]
Webpack is using next default settings for mainFields: ["module", "main"].
module is using import export,
main is using commonjs

if you are using webpack can you add exclude?
    rules: [{
      test: /\.(js|jsx)$/,
      exclude: /node_modules\/(?!react-facebook)/,
      use: [{
        loader: 'babel-loader',
      }],
    }, {

**Comment by KlonD90** [comment]
I have this trouble too. Can you fix this on your side?

**Comment by seeden** [comment]
Sure but I need more information. Do you have problem with webpack build? If yes can you share your babelrc config?

**Comment by brunosantanarj** [comment]
It's working, Thank you

**Comment by texmex44** [comment]
Same bug 

My babel rc : 

`{
  "presets": ["react", "es2015", "stage-0"]
}
`

**Comment by blackarcanis** [comment]
@texmex44  +1 same issue with webpack

**Comment by seeden** [comment]
@blackarcanis can you share your webpack config and webpack version?

**Comment by blackarcanis** [comment]
@seeden Same as @texmex44

**Comment by seeden** [comment]
@blackarcanis are you using webpack version 1.x?

**Comment by blackarcanis** [comment]
@seeden  1.13.3 to be exact

**Comment by robinknox** [comment]
I'm also seeing this issue when using this package in a Meteor 1.6 application

**Comment by seeden** [comment]
@robinknox  are you using webpack 1.x as well ?

**Comment by robinknox** [comment]
Hi @seeden I don't think Meteor uses Webpack. It uses a package called ecmascript https://docs.meteor.com/packages/ecmascript.html

**Comment by seeden** [comment]
I see. Import and export is not supported in meteor and webpack 1.x. OK
I will release new version in short run. It will transpile import export to commonjs.

**Comment by robinknox** [comment]
Thanks @seeden that'd be great. I did some reading on this and the Meteor devs made a conscious decision not to transpile packages in the node_modules folder for efficiency savings. They do have an open feature request here however I'm not sure when they'll get around to it https://github.com/meteor/meteor-feature-requests/issues/6

**Comment by texmex44** [comment]
@seeden I migrated to webpack 3 who solve the problem.

**Comment by seeden** [comment]
Yes, I know. This is the problem only for webpack 1 and meteor. I need to add commonjs because a lot of people are using old libs :(

**Comment by seeden** [comment]
Hi guys in new release 4.2.1 I removed modules for browser. Can you try it? Currently there are modules only for "module" which is supported by webpack  > 2.x. Let me know if it is working for you. IF no I will remove it from module as well.

**Comment by robinknox** [comment]
Thanks @seeden it's working for me in Meteor now, much appreciated.
