### ISSUE TITLE
Refused to display in frame ... Console Error

### ISSUE THREAD

**Issue by tazaka** [seeden/react-facebook#56]
Hi, please help me. If i use page plugin > 
```
<FacebookProvider appId={this.props.settings.FacebookAppId}>
  <Page href={this.props.settings.FacebookUrl} tabs="timeline" />
</FacebookProvider>
```
after some time i show this error in console (but everything works ...): 
![snimek obrazovky 2017-11-11 v 13 02 42](https://user-images.githubusercontent.com/4759260/32689229-ae8d0808-c6e0-11e7-8653-025dce3beb1b.png)
where am I making a mistake?
Thank you for your help :)

**Comment by seeden** [comment]
It looks like a problem in the facebook side

**Comment by chaddjohnson** [comment]
Surely there is something that can be done on this library's side of things. Otherwise every "Like" button would be broken across the web, and that's not the case.

**Comment by BrentFarese** [comment]
I am having this same issue right now.  Is there a solution?

**Comment by chaddjohnson** [comment]
I ended up running the initialization IIFE function in componentDidMount(), and I added the HTML to the render() function. Note that I have a common footer for every page in my app.

**Comment by seeden** [comment]
@chaddjohnson what is IIFE function ? Can you share your code? thanks

**Comment by chaddjohnson** [comment]
@seeden [Immediately-Invoked Function Expression](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression).

In index.html `<head>`:

```
<script>
!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
document,'script','https://connect.facebook.net/en_US/fbevents.js');
fbq('set', 'autoConfig', false, 'yourpixelidgoeshere');
fbq('init', 'yourpixelidgoeshere');
fbq('track', 'PageView');
</script>
```

In index.html `<body>`:

```html
<!-- For Facebook Pixel -->
<div id="fb-root"></div>

<!-- React app mount point -->
<main id="root"></main>
```

```javascript
// A component that is on every page.
class AppPage extends React.Component {
    componentDidMount() {
        // Record events with Facebook Pixel.
        fbq('trackCustom', 'EVENT_NAME', {value: 15.00, currency: 'USD'});
    }
}
```

**Comment by seeden** [comment]
react-facebook is loading facebook api as well. Maybe this is the main problem. Anyway I like custom events. Maybe we can add component for this functionality
```js
<FacebookEvent name="EVENT_NAME" options={{value: 12.00}} render={(onSend) => {(
  <button onClick={onSend}>
   click on me
</button>
)} /> 
```

What do you think?

**Comment by chaddjohnson** [comment]
@seeden That seems elegant to me. Though I am a bit new to React, and I am used to calling JavaScript functions directly. Proxying through a component and using HTML seems a bit weird...but, I guess that's the React way. It's how React Router works, for example, so I guess it's okay.

**Comment by Omar-Ali** [comment]
I'm facing the same issue now, is there a solution yet?

**Comment by seeden** [comment]
are you triggering events?

**Comment by Omar-Ali** [comment]
No, I'm just trying to embed a component which renders facebook chat widget.

**Comment by seeden** [comment]
Whole project was changed. Please try new version 6.x. Added subscribe component for facebook events.
