### ISSUE TITLE
appId ? PageId ? 

### ISSUE THREAD

**Issue by Gorbus** [seeden/react-facebook#58]
Hi, seems to be it's a great plugin but the doc is a bit minimalist. I am no facebook-savvy and I am struggling to set it up on my website.

I'd like to have the page feed on my website. A few question are rising:
- Can I have the page feed of any page or only page I own/am admin ?
- Do I need to create an app or is the page Id enough ? (I tried with page id but doesn't seem to work)
- If yes, what type of app ?  shall I link it to the page then ? and how (I tried to do a "page Application" but I don't see my page in the admin of the app to "link" the app to the page. the page is already existing.)
- is there any other configuration to do on my side more than jsut importing and adding the <FacebookProvider> and <Page> ?

Thanks in advance.

**Comment by seeden** [comment]
1. You can use any page feed.
2. If you want to use facebook sdk you need to have appId
3. You are able to link your page with your app (if they have similar name)
4. We are using same attributes like facebook
