### ISSUE TITLE
Props warning when using MessengerCheckbox

### ISSUE THREAD

**Issue by andersravn** [seeden/react-facebook#66]
I added the MessengerCheckbox plugin to my code as per the documentation (adding my own appId and pageId).

I'm getting the following errors/warnings:
![skaermbillede 2018-02-19 kl 14 54 15](https://user-images.githubusercontent.com/4648323/36381265-5c93baee-1585-11e8-91e5-e2632dbca188.png)

I can add the origin prop, and the first warning goes away. It's mostly the second warning that worries me.

Using React DOM 15.5.4 if that is relevant.

**Comment by nilaybrahmbhatt** [comment]
same here..

**Comment by seeden** [comment]
this component was updated in latest release please check the props
