### ISSUE TITLE
Comments not showing up on mobile screens

### ISSUE THREAD

**Issue by Jaikant** [seeden/react-facebook#70]
The comments dialog is not displaying on mobile screens. I tried setting mobile={true} but it doesn't work.

 Irrespective of what props  I pass in, I get the below error. (Even when I set width="100%")

```
Warning: Received `false` for a non-boolean attribute `width`.

If you want to write it to the DOM, pass a string instead: width="false" or width={value.toString()}.

If you used to conditionally omit it with width={condition && value}, pass width={condition ? value : undefined} instead.

```

**Comment by seeden** [comment]
Are you using latest version?

**Comment by Jaikant** [comment]
Yes, just set it up with
`   
 "react-facebook": "^5.0.3",
`

**Comment by seeden** [comment]
version 4.x was working for you?

**Comment by Jaikant** [comment]
I did not try the previous one, I could do that now.

Btw, I am using gatsbyjs, which is a static site generator. Could the below code be the issue?

```
export default function getCurrentHref() {
  if (!canUseDOM) {
    return 'https://www.facebook.com';
  }

  return location.href;
}

```

**Comment by seeden** [comment]
It will setup default href for you. If you have href param it will be skipped

**Comment by seeden** [comment]
Can you add your code to comment?

**Comment by Jaikant** [comment]
Here it is, 

```
            <FacebookProvider appId="975479032610796">
              <Comments href={`https://ootyultra.com${location.pathname}`} />
            </FacebookProvider>

```

the live url is here: [https://ootyultra.com/inspiration/balaji-thulasiraman](https://ootyultra.com/inspiration/balaji-thulasiraman)

**Comment by seeden** [comment]
Thanks I will check it

**Comment by seeden** [comment]
I see comments. I guess the problem is with your flexbox. Container of the components has width = '0%' from unknown reason. It is related to your css and not facebook.

**Comment by Jaikant** [comment]
ok! Thanks so much, possibly an interaction between my css and facebook's.

Below is what I have, which I will dig further into ..


```
          <div css={`display: flex; justify-content: center;`}>
            <FacebookProvider appId="1667204043574763">
              <Comments href={`https://localhost:3000${location.pathname}`} width="100%"/>
            </FacebookProvider>
          </div>

```

**Comment by seeden** [comment]
no problem :)
