### ISSUE TITLE
Issue going through UglifyJs

### ISSUE THREAD

**Issue by zjr** [seeden/react-facebook#71]
I'm having a bit of trouble with the package going through UglifyJs in WebPack v3.

Getting:
```
    ERROR in server.js from UglifyJs
    Unexpected token: name (Facebook_Facebook)
```

It doesn't like the `class` in `class Facebook_Facebook`. This started sometime in v4 of your package.  Why this particular package causes trouble I really don't know… we use quite a lot of packages and I'm sure yours isn't the only one w/ ES6 classes in it.

I don't have any more time to help with this, I'm sorry. Just passing along the info.  I know many other people have had trouble with UglifyJs getting hung up on ES6 stuff in packages, at the least this could help someone find their culprit one day.

**Comment by seeden** [comment]
Did you try latest 6.x version ?
