### ISSUE TITLE
Know if the user liked the page already

### ISSUE THREAD

**Issue by graphee-gabriel** [seeden/react-facebook#72]
Hello, I looked but I can't seem to find how to show the like button [only if the user did not liked the page already]. Did I miss something :-) ?

**Comment by seeden** [comment]
How are you doing this with vanilla facebook javascript sdk?

**Comment by graphee-gabriel** [comment]
Normally you're supposed to do it like this:
```
      window.FB.Event.subscribe('edge.create', function (href, widget) {
        console.log('user clicked like')
      })
      window.FB.Event.subscribe('edge.remove', function (href, widget) {
        console.log('user clicked unlike')
      })
```

But it's actually not what I need. I want to not show this widget if the user already liked the page.
But it seems actually impossible. In the sense the only way to do it would be to:
- Add facebook login with facebook permission 'user_likes' (which requires a review from facebook and a good reason to be requested)
- Have user login to your app
- Query facebook graph to check if this user has your page in the page they like
- Finally hide the widget then

So it means it only works for people who are logged in to your website using facbeook, and for now my app does not have any needs to login, and also includes google login.
So... Guess it has to stay all the time on my website even if it's freaking useless for me to show it when I already converted a user in a facebook like.

**Comment by seeden** [comment]
Added Subscribe component in 6.x version
