### ISSUE TITLE
ref= in CustomChat

### ISSUE THREAD

**Issue by thion** [seeden/react-facebook#74]
Why was `ref=` removed from CustomChat in https://github.com/seeden/react-facebook/commit/5720187148160983f51496e4a93e2d1c49c81675#diff-6ffc11bde0e25594959d8b28ca703e68?

It’s still supported as per https://developers.facebook.com/docs/messenger-platform/reference/web-plugins/#customer_chat

**Comment by seeden** [comment]
fixed
