### ISSUE TITLE
Token is undefined

### ISSUE THREAD

**Issue by fyn-dev** [seeden/react-facebook#76]
Before this piece of code works perfectly, but just recently I started getting error:

> Token is undefined   

Why? Before works everything well I didn't touch anything, but login element no longer working and always return this error.

How to fix this issue?

```
<FacebookProvider appId={config.facebook}>
          <Login
            scope="email"
            onResponse={this.checkEmail}
            // tslint:disable-next-line:no-any
            onError={(error: any) => {
              console.info('ISSUE IS HERE!!!!', error);
            }}
          >
            <Button 
              size="small" 
              className="btn-facebook" 
              loading={this.state.facebookLoading} 
              disabled={this.state.facebookLoading}
            >
              <Icon name="facebook f" size="large"/>
                facebook
            </Button>
          </Login>
        </FacebookProvider>
```

**Comment by seeden** [comment]
I will check it. Maybe you are using newest version of facebook sdk?

**Comment by olup** [comment]
I get the same error. However, if I click the button again, it goes through. Reloading page and trying again trigger the error, clicking again makes it work. And so on, and so on.

**Comment by fyn-dev** [comment]
@seeden I tried version 4 and 5 same issue.
@olup correct if you click again no issue after it.

**Comment by seeden** [comment]
Hi guys I completely changed whole project. Please try to use version 6.x. If you have this problem in the latest release please write me a comment and I will reopen this issue

**Comment by glenngijsberts** [comment]
Hey, same problem here using ^6.0.15.

**Comment by glenngijsberts** [comment]
After some investigation I've found out that's in there since 6.0.6 and probably also 6.0.5 and 6.0.4.
