### ISSUE TITLE
Multiple providers' app Id

### ISSUE THREAD

**Issue by olup** [seeden/react-facebook#77]
I am trying to implement a use case where we have different app ids on different pages. It seems that rendering a provider with a diferent app id doesn't pick up the changes, and we get stuck with the first invoked app Id. Is there any way to go around that ?

**Comment by seeden** [comment]
it is loading facebook sdk. and you are not able to use two on the one page

**Comment by olup** [comment]
I am aware of that. But my app being, as we can imagine, as SPA, I need a way to load a new app Id sdk on a diferent page. On this post i need to load theses comments depending on one specific appId, then on the login page I need to log my users with another app Id.
What I wonder is a way to de-register the sdk before loading a new one. Is there any way to make that work ?

**Comment by seeden** [comment]
I have no idea :) Try to find something and let me know
