### ISSUE TITLE
[ts] Could not find a declaration file for module 'react-facebook'.

### ISSUE THREAD

**Issue by createdbyjurand** [seeden/react-facebook#78]
I am building project using react + typescript

```
+-- @types/jest@22.2.3
+-- @types/node@10.1.2
+-- @types/react@16.3.14
+-- @types/react-dom@16.0.5
+-- @types/react-redux@6.0.0
+-- node-sass@4.9.0
+-- npm@6.0.1
+-- react@16.3.2
+-- react-dom@16.3.2
+-- react-facebook@5.0.3
+-- react-redux@5.0.7
+-- react-scripts-ts@2.16.0
+-- redux@4.0.0
+-- redux-devtools@3.4.1
-- typescript@2.8.3
```

// this statement
import FacebookProvider, { EmbeddedPost, MessageUs, Page } from 'react-facebook';

// makes this error:
[ts]
Could not find a declaration file for module 'react-facebook'. '*/node_modules/react-facebook/dist/index.js' implicitly has an 'any' type.
  Try `npm install @types/react-facebook` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-facebook';`

**Comment by seeden** [comment]
you can create a PR

**Comment by GeoMarkou** [comment]
I had the same problem and tried running `npm install @types/react-facebook` but the module didn't exist. I also tried creating a definitions file below. However it was apparent there are too many files for me to do externally with no knowledge of the internal structure of the module. Is there any plan to create a @types/react-facebook definition?

```
declare module 'react-facebook' {
    interface FacebookProviderProps {
        appId?: string,
        domain?: string,
        version?: string,
        cookie?: boolean,
        status?: boolean,
        xfbml?: boolean,
        language?: string,
        frictionlessRequests?: boolean,
        children?: any,
        wait?: boolean,
        debug?: boolean
    }
    export class FacebookProvider extends React.Component<FacebookProviderProps> {
    }
    interface GroupProps {
        href?: string,
        skin?: string,
        showSocialContext?: boolean,
        showMetaData?: boolean,
        width?: number | string,
        children?: any,
        style?: Object,
        handleParse?: Function
    }
    export class Group extends React.PureComponent<GroupProps> {
    }
}
```
