### ISSUE TITLE
Width should be a string

### ISSUE THREAD

**Issue by peteroid** [seeden/react-facebook#8]
According to the docs of Facebook Comments plugin, the width of the element could a string like "100%".

FYI: [https://developers.facebook.com/docs/plugins/comments/](https://developers.facebook.com/docs/plugins/comments/)

**Comment by peteroid** [comment]
For those who wants to use 100% as the width, you can override the propTypes in your jsx as below:

```
Comment.propTypes.width = React.PropTypes.oneOfType([
  React.PropTypes.string.isRequired,
  React.PropTypes.number.isRequired,
])
```

**Comment by seeden** [comment]
I am going to add this into the source code. But please in the feature create a pull-requests. Thank you @peteroid

**Comment by ramana459** [comment]
do u have corresponding type script definition?

**Comment by seeden** [comment]
no PR is welcome

**Comment by seeden** [comment]
merged
