### ISSUE TITLE
uninitialized components

### ISSUE THREAD

**Issue by maikelmclauflin** [seeden/react-facebook#80]
not sure how, but all i'm getting are uninitialized components
both with and without adding the script
```
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script src="https://platform.twitter.com/widgets.js"></script>
```
to the page the share button that comes along is always just unstyled. It renders fine, just doesn't do any calls to fb.
```
import FacebookProvider, { Share } from 'react-facebook'
```
```
          <FacebookProvider appId="123456789">
            <Share href={shareUrl}>
              <button type="button">Share</button>
            </Share>
          </FacebookProvider>
```
what am i doing wrong?
i am testing on localhost. perhaps that's it?
<img width="80" alt="screen shot 2018-06-21 at 9 34 55 am" src="https://user-images.githubusercontent.com/4896982/41725850-7379573a-7536-11e8-855f-507233b54adb.png">
Also, the button does nothing when clicked.

**Comment by seeden** [comment]
You need to use FacebookProvider only once in your application. Do not unmount it.

**Comment by seeden** [comment]
<Share> component is unstyled component. You can add your own style. If you want to use facebook share button with style you can use <Like> component
