### ISSUE TITLE
Using different locales

### ISSUE THREAD

**Issue by shevchuknine** [seeden/react-facebook#82]
For example, i have `<FacebookProvider language={this.state.locale}>...` & change `this.state.local` to another value. How to rerender provider with new props?

**Comment by seeden** [comment]
you need to "refresh" page because you need to redownload new sdk file

**Comment by shevchuknine** [comment]
So, i have a solution, but i'm not sure, that you will use it in your component :)

The main idea of my solution to make two .html files (for example `fb-ru.html` & `fb-en.html`) and to load they into `<iframe>`. HTML files will load sdk & set data into containers, iframe will reload comments without reload all react-page.  

Example code:
```
//file Comment.jsx
class Comment extends Component {
   state = {
      language: 'ru'
   }

   render() {
      const { language } = this.state;
      return (<iframe src={`fb-${language}.html`}/>)   
   }
};

//file fb-ru.html
<html>
<body>
<!--everything there from facebook dev page-->
<div id="fb-root"></div>
<div class="fb-comments" data-href="https://developers.facebook.com/docs/plugins/comments#configurator" data-numposts="5"></div>
<script>
    (function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = 'https://connect.facebook.net/ru_RU/sdk.js#xfbml=1&version=v3.0';
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'))
</script>
<!-- -->
</body>
</html>
```

That is all. I didn't find another solution.
Let me know if you implement solution of existing problem :)
