### ISSUE TITLE
comments-count deprecated

### ISSUE THREAD

**Issue by marcinkieruzel** [seeden/react-facebook#83]
Hi, is there any walk around for depresiation 
`<fb:comments-count> has been deprecated.`
?

**Comment by seeden** [comment]
I am not sure what do you mean. We can replace it with <span class="fb-comments-count" ...

**Comment by marcinkieruzel** [comment]
Hi Seeden, 
i'm useing component CommentCount like so 
```javascript
<CommentsCount href={`${window.location.origin}/post/${e.post.url}`}/>
```
but this gives me an error 
![screen](https://user-images.githubusercontent.com/25027015/44688960-2cc7c880-aa56-11e8-9cb5-0c08b1353421.png)
It just happen with CommentCount other components works fine.

**Comment by seeden** [comment]
You can use direct api call instead of component with Initialisation component. This component will stay in the project because deprecated not means broken
