### ISSUE TITLE
Sign Up button doesn't show for logged out user

### ISSUE THREAD

**Issue by zamirkhan** [seeden/react-facebook#92]
I'm using the Like button as in the example, but when the user is Logged out, the Sign Up button does not appear:

<img width="462" alt="screen shot 2018-09-18 at 4 38 02 pm" src="https://user-images.githubusercontent.com/2654175/45715051-45ad3080-bb61-11e8-9078-9fb0accd572d.png">

**Comment by seeden** [comment]
This is handled by facebook sdk.
