### ISSUE TITLE
facebook comment width fixed to 550px

### ISSUE THREAD

**Issue by dulx96** [seeden/react-facebook#94]
as the title, when i check element it shows up like this even i did't set width before. 
a few day ago the iframe element still 100% and it look very nice, can some one explain me how to fix that.

<span style="vertical-align: bottom; width: 550px; height: 330px;"><iframe name="f24c8fff69de52" width="550px" height="100px" frameborder="0" allowtransparency="true" allowfullscreen="true" scrolling="no" allow="encrypted-media" title="fb:comments Facebook Social Plugin" src="https://www.facebook.com/v2.9/plugins/comments.php?app_id=340409213030244&amp;channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter%2Fr%2FtrnHszv6jVd.js%3Fversion%3D42%23cb%3Dfbb24827d7ba28%26domain%3Dgatsby-starter-hero-blog.greglobinski.com%26origin%3Dhttps%253A%252F%252Fgatsby-starter-hero-blog.greglobinski.com%252Ff1e9dfad0ea2ac8%26relation%3Dparent.parent&amp;container_width=716&amp;height=100&amp;href=https%3A%2F%2Fgatsby-starter-hero-blog.greglobinski.com%2Fi-may-not-have-gone%2F&amp;locale=en_US&amp;sdk=joey&amp;title=I%20may%20not%20have%20gone%20where%20I%20intended%20to%20go%20-%20HeroBlog%20-%20GatsbyJS%20starter&amp;url=https%3A%2F%2Fgatsby-starter-hero-blog.greglobinski.com%2Fi-may-not-have-gone%2F&amp;version=v2.9&amp;width=550&amp;xid=https%253A%252F%252Fgatsby-starter-hero-blog.greglobinski.com%252Fi-may-not-have-gone%252F" style="border: none; visibility: visible; width: 550px; height: 330px;" class=""></iframe></span>

**Comment by wilko2205** [comment]
You can pass in a "width" prop into the Comments element to prevent it hardcoding the value:

`<Comments href="your-url" width="100%" />`

**Comment by seeden** [comment]
thanks @wilko2205
