### ISSUE TITLE
react-facebook not working on IE11

### ISSUE THREAD

**Issue by Jole83** [seeden/react-facebook#97]
react-facebook is not working on IE11. In console throws an error SCRIPT1002: Syntax error

**Comment by seeden** [comment]
are you using babel / webpack ?

**Comment by Jole83** [comment]
Yes I am using babel.

**Comment by seeden** [comment]
I will check it. Thanks

**Comment by Jole83** [comment]
Yes

пон, 22. окт 2018. у 13:34 Zlatko Fedor <notifications@github.com> је
написао/ла:

**Comment by radeno** [comment]
It looks like it is caused by `debug` package. Babel doesn't transpile arrow function in function formatArgs
You can see error.
```javascript
function formatArgs(args) {
...
...
	args[0].replace(/%[a-zA-Z%]/g, match => {
		if (match === '%%') {
			return;
		}
```

Do you need to use debug package? I see that it is used only once for whole project. https://github.com/seeden/react-facebook/blob/121d73bfe79199268820d46df82ac981af0c8cd4/src/Facebook.js#L61 I think you can use `console.error` instead

**Comment by seeden** [comment]
you are right. I will use version 3 instead of 4. They stopped to transpile code to ES5

**Comment by radeno** [comment]
Is it neccessary to use whole `debug` package just for one log expression ? Or am i wrong about that? Never use it before, maybe `debug` do some magic :)

**Comment by seeden** [comment]
It is standard if you do not want to remove console.log. You can turn on/off messages with simple DEBUG=facebook*,knex*,exress* variable. It is common package with 22,553,923 weekly downloads.

**Comment by radeno** [comment]
I understand it is "better" `console.log`. For removing console.log there is `babel-plugin-transform-remove-console`. Anyway i agree with you that `debug` is more user friendly than built-in `console`. So version 3 branch will fix issue.

Anyway @Jole83  you can downgrade debug version by add this to package.json
```json
  "resolutions": {
    "debug": "^3.2.6"
  }
```

**Comment by Jole83** [comment]
Thanks :)

**Comment by Jole83** [comment]
With resolutions doesn't work :( .
When can we expect next release?

**Comment by radeno** [comment]
@Jole83 it works for me. You need to do `yarn update` instead `yarn install`. It will update every package, but you can commit changes just for `debug`. Removing version 4 and change for version 3

**Comment by seeden** [comment]
next release will be today

**Comment by seeden** [comment]
Release new version

**Comment by MatthiasPdx** [comment]
I'm working with gatsby and it worked for me by adding the debug module to the gatsby-config.js 
See: https://www.gatsbyjs.org/packages/gatsby-plugin-compile-es6-packages/

My config in gatsby-config.js: 
    {
      resolve: `gatsby-plugin-compile-es6-packages`,
      options: {
        modules: ['debug'],
      },
    },
