### ISSUE TITLE
Customer Chat Plugin deprecation warning

### ISSUE THREAD

**Issue by phillytan** [seeden/react-facebook#99]
Facebook outputs this to my console when I use the plugin for the Customer Chat Plugin.

``` 
##########################
#  The CustomerChat plugin will soon be removed from the main Facebook SDK.
#  To continue using it please use the correct SDK URL.
#  For more details see https://fburl.com/customer-chat-sdk
##########################

**Comment by TrejoCode** [comment]
> 
> 
> Facebook outputs this to my console when I use the plugin for the Customer Chat Plugin.
> 
> ```
> ##########################
> #  The CustomerChat plugin will soon be removed from the main Facebook SDK.
> #  To continue using it please use the correct SDK URL.
> #  For more details see https://fburl.com/customer-chat-sdk
> ########################## 
> ```

Sí, al parecer existe un bug de parte de Facebook, NO de parte del desarrollador, NO es un issue de la librería, es de Facebook.

**Comment by hnliyuan** [comment]
请问有人能解决它吗？

**Comment by zsajjad** [comment]
I tried adding mentioned script beside this library, it causes some conflict and my login button keeps in loading state while chat works fine!
```
##########################
#  The CustomerChat plugin is no longer part of the main Facebook SDK.
#  To continue using it please use the correct SDK URL,
#  meaning replace sdk.js with sdk/xfbml.customerchat.js.
#  For more details see https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk
##########################
```

**Comment by GeoMarkou** [comment]
The CustomChat component doesn't seem to work anymore. I just get an error in the console below. Is there any plans to fix this? Or a workaround until it is resolved? I tried adding in a <script> src to the new javascript file but it seems to conflict and cause all react-facebook components to fail to load.

```
##########################
#  The CustomerChat plugin is no longer part of the main Facebook SDK.
#  To continue using it please use the correct SDK URL,
#  meaning replace sdk.js with sdk/xfbml.customerchat.js.
#  For more details see https://developers.facebook.com/docs/messenger-platform/discovery/customer-chat-plugin/sdk
##########################
```

Failed workaround:
```
<script src="https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js" id="facebook-jssdk-messenger"></script>
```

**Comment by mrsilver512** [comment]
Seems like there's a pull request for this issue: https://github.com/seeden/react-facebook/pull/132

**Comment by lmsfelipe** [comment]
Also having this warning and the chat is not showing up.

**Comment by seeden** [comment]
Fixed in the new version
